import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Share2, CheckCircle2, Loader, X, ExternalLink, ShieldCheck } from 'lucide-react';
import { api } from '../api/client';

const Youtube = ({ size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M23.498 6.163a3.003 3.003 0 0 0-2.11-2.107C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.388.511a3.003 3.003 0 0 0-2.11 2.107C0 8.051 0 12 0 12s0 3.949.502 5.837a3.003 3.003 0 0 0 2.11 2.107c1.883.511 9.388.511 9.388.511s7.505 0 9.388-.511a3.003 3.003 0 0 0 2.11-2.107c.502-1.888.502-5.837.502-5.837s0-3.949-.502-5.837zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
  </svg>
);

const Facebook = ({ size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
  </svg>
);

const Instagram = ({ size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
  </svg>
);

export default function SocialPublishingPanel({ clip, onClose }) {
  const [connections, setConnections] = useState({
    youtube: null,
    facebook: null,
    instagram: null,
  });

  const [selectedPlatforms, setSelectedPlatforms] = useState({
    youtube: false,
    facebook: false,
    instagram: false,
  });

  const [title, setTitle] = useState(clip.title || 'New Highlight Clip');
  const [description, setDescription] = useState(
    'Check out this viral highlight generated by Harvest AI! #shorts #viral #ai'
  );
  const [privacy, setPrivacy] = useState('public');
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishProgress, setPublishProgress] = useState([]);
  const [publishSuccess, setPublishSuccess] = useState(false);
  const [shareUrls, setShareUrls] = useState({});

  // Load connected accounts from Database (real storage)
  useEffect(() => {
    const loadConnections = async () => {
      try {
        const data = await api.getUserConnections(1);
        const loaded = { youtube: null, facebook: null, instagram: null };
        const preSelect = { youtube: false, facebook: false, instagram: false };
        data.forEach((conn) => {
          loaded[conn.platform] = {
            name: conn.account_name,
            handle: conn.account_handle,
            avatar: conn.account_avatar,
            credentials: conn.credentials || {},
          };
          preSelect[conn.platform] = true;
        });
        setConnections(loaded);
        setSelectedPlatforms(preSelect);
      } catch (e) {
        console.error('Failed to load connections from DB:', e);
      }
    };
    loadConnections();
  }, []);

  // Simulated Popup OAuth flow
  const handleConnect = (platform) => {
    const w = 550;
    const h = 720;
    const left = window.screen.width / 2 - w / 2;
    const top = window.screen.height / 2 - h / 2;

    const loginUrl = `https://localhost:8000/api/v1/users/auth/${platform}/login?user_id=1`;

    const popup = window.open(
      loginUrl,
      `Connect ${platform}`,
      `width=${w},height=${h},top=${top},left=${left},status=no,menubar=no,toolbar=no`
    );

    if (!popup) {
      alert('Please disable your popup blocker to log in.');
      return;
    }

    // Listen for connection success/fail requests from popup
    const handleAuthMessage = async (event) => {
      // Direct authentication success from backend redirect OAuth callback
      if (event.data?.type === 'HARVEST_AUTH_SUCCESS' && event.data?.platform === platform) {
        try {
          clearInterval(pollInterval);
          // Load updated connections from backend DB
          const data = await api.getUserConnections(1);
          const loaded = { youtube: null, facebook: null, instagram: null };
          const newSelect = { youtube: false, facebook: false, instagram: false };
          data.forEach((conn) => {
            loaded[conn.platform] = {
              name: conn.account_name,
              handle: conn.account_handle,
              avatar: conn.account_avatar,
              credentials: conn.credentials || {},
            };
            newSelect[conn.platform] = true;
          });
          setConnections(loaded);
          setSelectedPlatforms(newSelect);
        } catch (e) {
          console.error("Failed to sync connection after live login:", e);
        }
        window.removeEventListener('message', handleAuthMessage);
      } else if (event.data?.type === 'HARVEST_AUTH_FAILURE') {
        clearInterval(pollInterval);
        alert(`Authentication failed: ${event.data.error}`);
        window.removeEventListener('message', handleAuthMessage);
      }
    };

    window.addEventListener('message', handleAuthMessage);

    // Start polling the backend DB for connection changes as a fallback/robust mechanism
    const pollInterval = setInterval(async () => {
      if (popup.closed) {
        clearInterval(pollInterval);
        return;
      }
      try {
        const data = await api.getUserConnections(1);
        const found = data.find((conn) => conn.platform === platform);
        if (found) {
          clearInterval(pollInterval);
          const loaded = { youtube: null, facebook: null, instagram: null };
          const newSelect = { youtube: false, facebook: false, instagram: false };
          data.forEach((conn) => {
            loaded[conn.platform] = {
              name: conn.account_name,
              handle: conn.account_handle,
              avatar: conn.account_avatar,
              credentials: conn.credentials || {},
            };
            newSelect[conn.platform] = true;
          });
          setConnections(loaded);
          setSelectedPlatforms(newSelect);
          try {
            popup.close();
          } catch (e) {
            console.error("Failed to close popup:", e);
          }
          window.removeEventListener('message', handleAuthMessage);
        }
      } catch (e) {
        console.error("Failed to poll connection status:", e);
      }
    }, 2000);
  };


  const handleDisconnect = async (platform) => {
    try {
      await api.deleteUserConnection(1, platform);
      setConnections((prev) => ({
        ...prev,
        [platform]: null,
      }));
      setSelectedPlatforms((prev) => ({ ...prev, [platform]: false }));
    } catch (e) {
      console.error("Failed to disconnect from DB:", e);
      alert("Failed to disconnect from database.");
    }
  };

  const togglePlatformSelection = (platform) => {
    if (!connections[platform]) {
      handleConnect(platform);
      return;
    }
    setSelectedPlatforms((prev) => ({
      ...prev,
      [platform]: !prev[platform],
    }));
  };

  const handlePublish = async () => {
    const activePlatforms = Object.keys(selectedPlatforms).filter((k) => selectedPlatforms[k]);
    if (activePlatforms.length === 0) {
      alert('Please select at least one connected social platform to publish to.');
      return;
    }

    // Extract custom tokens/credentials if the connected account is configured with them
    const platformConfigs = {};
    activePlatforms.forEach((p) => {
      const conn = connections[p];
      if (conn && conn.credentials) {
        Object.keys(conn.credentials).forEach((k) => {
          platformConfigs[k] = conn.credentials[k];
        });
      }
    });

    setIsPublishing(true);
    setPublishSuccess(false);
    setPublishProgress([]);

    // Initialize progress items
    const steps = [];
    activePlatforms.forEach((p) => {
      steps.push({ platform: p, stage: 'handshake', label: 'Connecting to server API...', status: 'running' });
    });
    setPublishProgress(steps);

    try {
      // Trigger background publishing task on backend
      const res = await api.publishClip(clip.id, activePlatforms, title, description, privacy, platformConfigs);
      const taskId = res.task_id;

      // Start real polling loop to track the backend publish state
      let attempt = 0;
      const maxAttempts = 100; // Poll up to 5 minutes

      // Update progress state to uploading
      setPublishProgress(activePlatforms.map(p => ({
        platform: p,
        stage: 'uploading',
        label: 'Uploading and processing video on platform servers...',
        status: 'running'
      })));

      const interval = setInterval(async () => {
        try {
          const clipData = await api.getClip(clip.id);
          const urls = clipData.published_urls || {};

          attempt++;
          if (attempt >= maxAttempts) {
            clearInterval(interval);
            alert("Publishing timed out on the backend server.");
            setIsPublishing(false);
            return;
          }

          // Check if all selected platforms have finished publishing (either succeeded or failed)
          const allDone = activePlatforms.every(p => !!urls[p]);

          setPublishProgress((prev) => {
            return prev.map(item => {
              const platformUrl = urls[item.platform];
              if (platformUrl) {
                if (platformUrl.startsWith('error:')) {
                  return {
                    ...item,
                    stage: 'failed',
                    label: `Publishing failed: ${platformUrl.substring(6)}`,
                    status: 'failed'
                  };
                }
                return {
                  ...item,
                  stage: 'success',
                  label: 'Video successfully published!',
                  status: 'completed'
                };
              }
              // Still running
              return {
                ...item,
                stage: 'indexing',
                label: `Processing on ${getPlatformLabel(item.platform)} API servers...`,
                status: 'running'
              };
            });
          });

          if (allDone) {
            clearInterval(interval);
            setIsPublishing(false);
            const hasSuccess = Object.values(urls).some(url => url && !url.startsWith('error:'));
            if (hasSuccess) {
              setPublishSuccess(true);
              const successUrls = {};
              Object.keys(urls).forEach(p => {
                if (urls[p] && !urls[p].startsWith('error:')) {
                  successUrls[p] = urls[p];
                }
              });
              setShareUrls(successUrls);
            } else {
              alert("All social publishing requests failed. Please check the connection credentials and try again.");
            }
          }
        } catch (err) {
          console.error("Error polling publishing task:", err);
        }
      }, 3000);

    } catch (e) {
      console.error(e);
      alert('Publishing failed: ' + e.message);
      setIsPublishing(false);
    }
  };

  const getPlatformIcon = (platform, size = 20) => {
    switch (platform) {
      case 'youtube':
        return <Youtube size={size} color="#ff0000" />;
      case 'facebook':
        return <Facebook size={size} color="#1877f2" />;
      case 'instagram':
        return <Instagram size={size} color="#e1306c" />;
      default:
        return null;
    }
  };

  const getPlatformLabel = (platform) => {
    switch (platform) {
      case 'youtube':
        return 'YouTube Shorts';
      case 'facebook':
        return 'Facebook Reels';
      case 'instagram':
        return 'Instagram Reels';
      default:
        return '';
    }
  };

  return (
    <div className="glass-panel" style={{ background: '#12121a', border: '1px solid rgba(255, 255, 255, 0.1)', padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', width: '100%', position: 'relative' }}>

      {onClose && (
        <button
          onClick={onClose}
          style={{ position: 'absolute', top: 20, right: 20, background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer' }}
        >
          <X size={20} />
        </button>
      )}

      <div>
        <h3 style={{ margin: 0, fontSize: '1.4rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
          <Share2 size={22} color="var(--accent-color)" /> Social Media Publishing
        </h3>
        <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
          Directly publish this short-form vertical video to your profiles
        </p>
      </div>

      {!isPublishing && !publishSuccess ? (
        <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap' }}>
          {/* Left Column: Platform Selection & Login */}
          <div style={{ flex: 1.2, display: 'flex', flexDirection: 'column', gap: '1.2rem', minWidth: 260 }}>
            <h4 style={{ margin: 0, fontSize: '0.95rem', color: '#c084fc', textTransform: 'uppercase', fontWeight: 700 }}>
              1. Choose Platforms
            </h4>

            {['youtube', 'facebook', 'instagram'].map((plat) => {
              const connected = connections[plat];
              const isSelected = selectedPlatforms[plat];

              return (
                <div
                  key={plat}
                  onClick={() => togglePlatformSelection(plat)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '1rem',
                    background: isSelected ? 'rgba(139, 92, 246, 0.08)' : 'rgba(255, 255, 255, 0.02)',
                    border: `1px solid ${isSelected ? '#8b5cf6' : 'rgba(255, 255, 255, 0.08)'}`,
                    borderRadius: 12,
                    cursor: 'pointer',
                    transition: 'all 0.2s',
                  }}
                  onMouseEnter={(e) => {
                    if (!isSelected) e.currentTarget.style.borderColor = 'rgba(255,255,255,0.2)';
                  }}
                  onMouseLeave={(e) => {
                    if (!isSelected) e.currentTarget.style.borderColor = 'rgba(255,255,255,0.08)';
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
                    <div style={{ padding: '0.4rem', background: 'rgba(0,0,0,0.2)', borderRadius: '8px' }}>
                      {getPlatformIcon(plat, 24)}
                    </div>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: '0.9rem' }}>{getPlatformLabel(plat)}</div>
                      <div style={{ fontSize: '0.75rem', color: connected ? '#10b981' : '#64748b' }}>
                        {connected ? `Connected: ${connected.name}` : 'Not Connected'}
                      </div>
                    </div>
                  </div>

                  {connected ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      {isSelected && <span style={{ color: '#8b5cf6', fontSize: '1.2rem' }}>OK</span>}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDisconnect(plat);
                        }}
                        style={{
                          background: 'rgba(239, 68, 68, 0.1)',
                          color: '#ef4444',
                          border: 'none',
                          padding: '4px 8px',
                          borderRadius: 6,
                          fontSize: '0.7rem',
                          cursor: 'pointer',
                          fontWeight: 'bold',
                        }}
                      >
                        Disconnect
                      </button>
                    </div>
                  ) : (
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleConnect(plat);
                      }}
                      style={{
                        background: 'rgba(255, 255, 255, 0.05)',
                        border: '1px solid rgba(255, 255, 255, 0.15)',
                        color: 'white',
                        padding: '6px 12px',
                        borderRadius: 8,
                        fontSize: '0.75rem',
                        cursor: 'pointer',
                        fontWeight: 'bold',
                      }}
                    >
                      Connect
                    </button>
                  )}
                </div>
              );
            })}
          </div>

          {/* Right Column: Metadata details */}
          <div style={{ flex: 1.8, display: 'flex', flexDirection: 'column', gap: '1rem', minWidth: 300 }}>
            <h4 style={{ margin: 0, fontSize: '0.95rem', color: '#c084fc', textTransform: 'uppercase', fontWeight: 700 }}>
              2. Metadata & SEO Settings
            </h4>

            {selectedPlatforms.youtube && (
              <div>
                <label style={{ display: 'block', marginBottom: '0.3rem', fontSize: '0.8rem', color: '#94a3b8' }}>
                  YouTube Shorts Title (Max 100)
                </label>
                <input
                  type="text"
                  className="input-field"
                  value={title}
                  maxLength={100}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Crazy Gaming Clip! #shorts"
                  style={{ width: '100%', fontSize: '0.85rem' }}
                />
              </div>
            )}

            <div>
              <label style={{ display: 'block', marginBottom: '0.3rem', fontSize: '0.8rem', color: '#94a3b8' }}>
                Description / Caption
              </label>
              <textarea
                className="input-field"
                value={description}
                rows={4}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Enter caption or post text..."
                style={{ width: '100%', fontSize: '0.85rem', resize: 'none', fontFamily: 'inherit' }}
              />
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#64748b', marginTop: '0.2rem' }}>
                <span>Use hashtags for viral reach!</span>
                <span>{description.length} chars</span>
              </div>
            </div>

            {selectedPlatforms.youtube && (
              <div>
                <label style={{ display: 'block', marginBottom: '0.3rem', fontSize: '0.8rem', color: '#94a3b8' }}>
                  Shorts Privacy Level
                </label>
                <select
                  value={privacy}
                  onChange={(e) => setPrivacy(e.target.value)}
                  style={{
                    background: 'rgba(0,0,0,0.3)',
                    color: 'white',
                    border: '1px solid rgba(255,255,255,0.1)',
                    borderRadius: '8px',
                    padding: '0.5rem',
                    width: '100%',
                    fontSize: '0.85rem',
                    outline: 'none',
                  }}
                >
                  <option value="public">Public (Immediate release)</option>
                  <option value="unlisted">Unlisted (Link access only)</option>
                  <option value="private">Private (Only you can view)</option>
                </select>
              </div>
            )}

            <button
              onClick={handlePublish}
              className="btn-neon"
              style={{
                width: '100%',
                padding: '0.8rem',
                fontSize: '0.95rem',
                fontWeight: 'bold',
                marginTop: '0.5rem',
              }}
            >
              Publish Selected Platforms
            </button>
          </div>
        </div>
      ) : isPublishing ? (
        /* Publishing Loader Stage */
        <div style={{ textAlign: 'center', padding: '2rem 1rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ repeat: Infinity, duration: 2, ease: 'linear' }}
            style={{ width: 48, height: 48, borderRadius: '50%', border: '3px solid rgba(139,92,246,0.2)', borderTopColor: '#8b5cf6', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          />
          <div>
            <h4 style={{ margin: 0, fontSize: '1.2rem', color: '#fff' }}>Publishing in Progress</h4>
            <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: '#94a3b8' }}>
              Transmitting video chunks and applying SEO configs to platforms
            </p>
          </div>

          <div style={{ width: '100%', maxWidth: 450, background: 'rgba(0,0,0,0.3)', padding: '1.2rem', borderRadius: 12, border: '1px solid rgba(255,255,255,0.05)', display: 'flex', flexDirection: 'column', gap: '0.8rem', textAlign: 'left' }}>
            {publishProgress.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  {getPlatformIcon(item.platform, 16)}
                  <span style={{ fontWeight: 600 }}>{getPlatformLabel(item.platform)}:</span>
                  <span style={{ color: '#cbd5e1' }}>{item.label}</span>
                </div>
                {item.status === 'completed' ? (
                  <span style={{ color: '#10b981', fontWeight: 600 }}>Done</span>
                ) : item.status === 'failed' ? (
                  <span style={{ color: '#ef4444', fontWeight: 600 }}>Failed</span>
                ) : (
                  <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1.5, ease: 'linear' }}>
                    <Loader size={14} color="#8b5cf6" />
                  </motion.div>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        /* Success State */
        <div style={{ textAlign: 'center', padding: '2.5rem 1rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
          <div style={{ width: 64, height: 64, borderRadius: '50%', background: 'rgba(16,185,129,0.15)', border: '2px solid #10b981', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#10b981' }}>
            <CheckCircle2 size={32} />
          </div>
          <div>
            <h4 style={{ margin: 0, fontSize: '1.3rem', color: '#fff' }}>Publication Success!</h4>
            <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: '#94a3b8' }}>
              Your clip parts have been published and are now processing on servers
            </p>
          </div>

          <div style={{ width: '100%', maxWidth: 450, display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
            {Object.keys(shareUrls).map((p) => (
              <a
                key={p}
                href={shareUrls[p]}
                target="_blank"
                rel="noreferrer"
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '1rem',
                  background: 'rgba(255,255,255,0.02)',
                  border: '1px solid rgba(255,255,255,0.08)',
                  borderRadius: 10,
                  color: 'white',
                  textDecoration: 'none',
                  fontSize: '0.9rem',
                  transition: 'background 0.2s',
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = 'rgba(255,255,255,0.05)')}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'rgba(255,255,255,0.02)')}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
                  {getPlatformIcon(p, 20)}
                  <span style={{ fontWeight: 600 }}>View on {getPlatformLabel(p)}</span>
                </div>
                <ExternalLink size={16} color="#94a3b8" />
              </a>
            ))}
          </div>

          <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem' }}>
            <button
              onClick={() => {
                setPublishSuccess(false);
                setIsPublishing(false);
              }}
              style={{
                padding: '0.6rem 1.5rem',
                background: 'rgba(255,255,255,0.05)',
                border: '1px solid rgba(255,255,255,0.15)',
                borderRadius: 8,
                color: 'white',
                cursor: 'pointer',
                fontSize: '0.85rem',
                fontWeight: 600,
              }}
            >
              Publish Again
            </button>
            {onClose && (
              <button
                onClick={onClose}
                className="btn-neon"
                style={{ padding: '0.6rem 1.5rem', fontSize: '0.85rem' }}
              >
                Close Panel
              </button>
            )}
          </div>
        </div>
      )}

      {/* Security note */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', justifyContent: 'center', borderTop: '1px solid rgba(255,255,255,0.04)', paddingTop: '1rem', fontSize: '0.75rem', color: '#475569' }}>
        <ShieldCheck size={14} /> Encrypted API Handshake. Content authorized via verified developer OAuth credentials.
      </div>
    </div>
  );
}
