import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Share2, CheckCircle2, Loader, X, ExternalLink, ShieldCheck } from 'lucide-react';
import { api } from '../api/client';

const Youtube = ({ size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M23.498 6.163a3.003 3.003 0 0 0-2.11-2.107C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.388.511a3.003 3.003 0 0 0-2.11 2.107C0 8.051 0 12 0 12s0 3.949.502 5.837a3.003 3.003 0 0 0 2.11 2.107c1.883.511 9.388.511 9.388.511s7.505 0 9.388-.511a3.003 3.003 0 0 0 2.11-2.107c.502-1.888.502-5.837.502-5.837s0-3.949-.502-5.837zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
  </svg>
);

const Facebook = ({ size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" {...props}>
    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
  </svg>
);

const Instagram = ({ size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
  </svg>
);

export default function SocialPublishingPanel({ clip, onClose }) {
  const [connections, setConnections] = useState({
    youtube: null,
    facebook: null,
    instagram: null,
  });

  const [selectedPlatforms, setSelectedPlatforms] = useState({
    youtube: false,
    facebook: false,
    instagram: false,
  });

  const [title, setTitle] = useState(clip.title || 'New Highlight Clip');
  const [description, setDescription] = useState(
    'Check out this viral highlight generated by Harvest AI! #shorts #viral #ai'
  );
  const [privacy, setPrivacy] = useState('public');
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishProgress, setPublishProgress] = useState([]);
  const [publishSuccess, setPublishSuccess] = useState(false);
  const [shareUrls, setShareUrls] = useState({});

  // Load connected accounts from Database (real storage)
  useEffect(() => {
    const loadConnections = async () => {
      try {
        const data = await api.getUserConnections(1);
        const loaded = { youtube: null, facebook: null, instagram: null };
        data.forEach((conn) => {
          loaded[conn.platform] = {
            name: conn.account_name,
            handle: conn.account_handle,
            avatar: conn.account_avatar,
            credentials: conn.credentials || {},
          };
        });
        setConnections(loaded);
      } catch (e) {
        console.error('Failed to load connections from DB:', e);
      }
    };
    loadConnections();
  }, []);

  // Simulated Popup OAuth flow
  const handleConnect = (platform) => {
    const w = 550;
    const h = 720;
    const left = window.screen.width / 2 - w / 2;
    const top = window.screen.height / 2 - h / 2;

    const popup = window.open(
      '',
      `Connect ${platform}`,
      `width=${w},height=${h},top=${top},left=${left},status=no,menubar=no,toolbar=no`
    );

    if (!popup) {
      alert('Please disable your popup blocker to log in.');
      return;
    }

    const platformLabels = {
      youtube: 'Google (YouTube Shorts)',
      facebook: 'Meta (Facebook Reels)',
      instagram: 'Instagram Creator API',
    };

    const brandColors = {
      youtube: '#ff0000',
      facebook: '#1877f2',
      instagram: '#e1306c',
    };

    // Render advanced inputs based on platform
    let advancedFieldsHTML = '';
    if (platform === 'youtube') {
      advancedFieldsHTML = `
        <div class="input-group">
          <label>OAuth Access Token</label>
          <input type="text" id="youtube_access_token" placeholder="ya29.a0AXgv..." />
        </div>
      `;
    } else if (platform === 'facebook') {
      advancedFieldsHTML = `
        <div class="input-group">
          <label>Page Access Token</label>
          <input type="text" id="facebook_access_token" placeholder="EAAG..." />
        </div>
        <div class="input-group">
          <label>Facebook Page ID</label>
          <input type="text" id="facebook_page_id" placeholder="1029384756..." />
        </div>
      `;
    } else if (platform === 'instagram') {
      advancedFieldsHTML = `
        <div class="input-group">
          <label>Instagram/Facebook User Access Token</label>
          <input type="text" id="instagram_access_token" placeholder="IGQV..." />
        </div>
        <div class="input-group">
          <label>Instagram Business Account ID</label>
          <input type="text" id="instagram_business_id" placeholder="178414..." />
        </div>
        <div class="input-group">
          <label>Public Video URL (Optional)</label>
          <input type="text" id="public_video_url" placeholder="https://mycdn.com/shorts/video.mp4" />
        </div>
      `;
    }

    popup.document.write(`
      <html>
        <head>
          <title>Authorize Harvest AI</title>
          <style>
            body {
              background-color: #0d0d12;
              color: #ffffff;
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              min-height: 100vh;
              margin: 0;
              padding: 20px;
              box-sizing: border-box;
              text-align: center;
            }
            .card {
              background: #13131c;
              border: 1px solid rgba(255, 255, 255, 0.08);
              border-radius: 20px;
              padding: 30px;
              max-width: 440px;
              width: 100%;
              box-shadow: 0 20px 50px rgba(0,0,0,0.6);
              box-sizing: border-box;
            }
            h2 {
              margin-top: 0;
              font-size: 1.4rem;
              font-weight: 700;
              letter-spacing: -0.025em;
            }
            p {
              color: #94a3b8;
              font-size: 0.85rem;
              line-height: 1.6;
              margin-bottom: 25px;
            }
            .brand-logo {
              font-size: 3rem;
              margin-bottom: 15px;
            }
            .btn {
              color: white;
              border: none;
              padding: 12px 20px;
              border-radius: 10px;
              font-weight: 600;
              cursor: pointer;
              font-size: 0.9rem;
              width: 100%;
              transition: all 0.2s ease;
              box-sizing: border-box;
              outline: none;
            }
            .btn-live {
              background: ${brandColors[platform]};
            }
            .btn-live:hover {
              opacity: 0.9;
              transform: translateY(-1px);
            }
            .btn-cancel {
              background: transparent;
              border: 1px solid rgba(255,255,255,0.15);
              color: #94a3b8;
              margin-top: 15px;
            }
            .btn-cancel:hover {
              background: rgba(255,255,255,0.03);
              color: white;
            }
            .permission-item {
              display: flex;
              align-items: center;
              gap: 10px;
              text-align: left;
              background: rgba(255,255,255,0.02);
              padding: 10px 14px;
              border-radius: 10px;
              margin-top: 10px;
              font-size: 0.8rem;
              border: 1px solid rgba(255,255,255,0.04);
            }
            .advanced-container {
              margin-top: 20px;
              text-align: left;
            }
            .advanced-toggle {
              cursor: pointer;
              color: #c084fc;
              font-size: 0.8rem;
              user-select: none;
              font-weight: 600;
              display: flex;
              align-items: center;
              gap: 5px;
              justify-content: center;
              margin-bottom: 10px;
              transition: color 0.2s;
            }
            .advanced-toggle:hover {
              color: #a855f7;
            }
            .advanced-fields {
              display: none;
              background: rgba(0, 0, 0, 0.2);
              border: 1px solid rgba(255, 255, 255, 0.05);
              border-radius: 12px;
              padding: 18px;
              margin-top: 10px;
            }
            .input-group {
              margin-bottom: 12px;
            }
            .input-group label {
              display: block;
              font-size: 0.75rem;
              color: #94a3b8;
              margin-bottom: 6px;
              font-weight: 500;
            }
            .input-group input {
              width: 100%;
              background: #09090d;
              border: 1px solid rgba(255, 255, 255, 0.12);
              border-radius: 8px;
              color: white;
              padding: 10px 12px;
              font-size: 0.8rem;
              box-sizing: border-box;
              outline: none;
              transition: border-color 0.2s;
            }
            .input-group input:focus {
              border-color: #8b5cf6;
            }
            .spinner {
              border: 3px solid rgba(139, 92, 246, 0.1);
              width: 40px;
              height: 40px;
              border-radius: 50%;
              border-left-color: #8b5cf6;
              animation: spin 1s linear infinite;
              margin: 25px auto 15px;
            }
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          </style>
        </head>
        <body>
          <div class="card">
            <div class="brand-logo">${platform === 'youtube' ? '🎥' : platform === 'instagram' ? '📸' : '👤'}</div>
            <h2>Sign in with ${platformLabels[platform]}</h2>
            <p>Harvest AI requests permission to manage and upload short-form videos to your profile.</p>
            
            <div id="error-container" style="display: none; background: rgba(239, 68, 68, 0.1); border: 1px solid rgba(239, 68, 68, 0.2); padding: 12px; border-radius: 10px; color: #f87171; font-size: 0.8rem; text-align: left; margin-bottom: 20px; line-height: 1.4;">
              <strong>Verification Failed:</strong> <span id="error-msg"></span>
            </div>

            <div id="loader-container" style="display: none; padding: 20px 0;">
              <div class="spinner"></div>
              <div id="loader-text" style="color: #a78bfa; font-size: 0.95rem; font-weight: 500;">Verifying...</div>
            </div>

            <div id="success-container" style="display: none; padding: 20px 0;">
              <div style="font-size: 3rem; margin-bottom: 10px;">✨</div>
              <div style="color: #10b981; font-size: 1.1rem; font-weight: bold;">Connection Successful!</div>
              <p style="font-size: 0.8rem; color: #64748b; margin-top: 5px; margin-bottom: 0;">Closing popup...</p>
            </div>

            <div id="btn-container">
              <button class="btn btn-live" id="btn-live">Verify Server Settings (.env)</button>
              <button class="btn" id="btn-sandbox" style="background: rgba(139, 92, 246, 0.15); border: 1px solid rgba(139, 92, 246, 0.25); color: #c084fc; margin-top: 10px;">Connect Sandbox Mode (Simulated)</button>
              
              <div class="advanced-container">
                <div class="advanced-toggle" id="advanced-toggle">► Paste Custom Developer Tokens</div>
                <div class="advanced-fields" id="advanced-fields">
                  ${advancedFieldsHTML}
                  <button class="btn" id="btn-auth" style="background: #8b5cf6; margin-top: 10px;">Verify Custom Token</button>
                </div>
              </div>

              <div class="permission-item">
                <span>✔️</span>
                <span>Manage vertical videos and metadata</span>
              </div>
              <div class="permission-item">
                <span>✔️</span>
                <span>Publish Reels / Shorts on your behalf</span>
              </div>

              <button class="btn btn-cancel" onclick="window.close()">Cancel</button>
            </div>
          </div>

          <script>
            const toggle = document.getElementById('advanced-toggle');
            const fields = document.getElementById('advanced-fields');
            toggle.addEventListener('click', () => {
              const isHidden = fields.style.display === 'none' || fields.style.display === '';
              fields.style.display = isHidden ? 'block' : 'none';
              toggle.innerText = isHidden ? '▼ Hide Advanced Options' : '► Paste Custom Developer Tokens';
            });

            // Listen for replies from parent
            window.addEventListener('message', (event) => {
              if (event.data?.type === 'HARVEST_AUTH_SUCCESS') {
                document.getElementById('loader-container').style.display = 'none';
                document.getElementById('success-container').style.display = 'block';
                setTimeout(() => window.close(), 1200);
              } else if (event.data?.type === 'HARVEST_AUTH_FAILURE') {
                document.getElementById('error-msg').innerText = event.data.error || 'Verification failed.';
                document.getElementById('error-container').style.display = 'block';
                document.getElementById('btn-container').style.display = 'block';
                document.getElementById('loader-container').style.display = 'none';
              }
            });

            function showLoader(message) {
              document.getElementById('error-container').style.display = 'none';
              document.getElementById('btn-container').style.display = 'none';
              document.getElementById('loader-container').style.display = 'block';
              document.getElementById('loader-text').innerText = message;
            }

            // Connect using Server Settings (Live OAuth Redirect)
            document.getElementById('btn-live').addEventListener('click', () => {
              showLoader('Redirecting to Google/Meta authentication services...');
              window.location.href = 'http://localhost:8000/api/v1/users/auth/${platform}/login?user_id=1';
            });

            // Connect in Sandbox Mode
            document.getElementById('btn-sandbox').addEventListener('click', () => {
              showLoader('Connecting simulated sandbox account...');
              window.opener.postMessage({
                type: 'HARVEST_AUTH_REQUEST',
                platform: '${platform}',
                credentials: { is_sandbox: true }
              }, '*');
            });

            // Connect using Custom Credentials
            document.getElementById('btn-auth').addEventListener('click', () => {
              const credentials = {};
              
              if ('${platform}' === 'youtube') {
                const token = document.getElementById('youtube_access_token')?.value?.trim();
                if (token) credentials.youtube_access_token = token;
              } else if ('${platform}' === 'facebook') {
                const token = document.getElementById('facebook_access_token')?.value?.trim();
                const pageId = document.getElementById('facebook_page_id')?.value?.trim();
                if (token) credentials.facebook_access_token = token;
                if (pageId) credentials.facebook_page_id = pageId;
              } else if ('${platform}' === 'instagram') {
                const token = document.getElementById('instagram_access_token')?.value?.trim();
                const bizId = document.getElementById('instagram_business_id')?.value?.trim();
                const videoUrl = document.getElementById('public_video_url')?.value?.trim();
                if (token) credentials.instagram_access_token = token;
                if (bizId) credentials.instagram_business_id = bizId;
                if (videoUrl) credentials.public_video_url = videoUrl;
              }

              showLoader('Verifying custom credentials with Google/Meta APIs...');
              window.opener.postMessage({
                type: 'HARVEST_AUTH_REQUEST',
                platform: '${platform}',
                credentials: credentials
              }, '*');
            });
          </script>
        </body>
      </html>
    `);

    // Listen for connection success/fail requests from popup
    const handleAuthMessage = async (event) => {
      // 1. Handshake request from popup (Sandbox / Custom keys validation)
      if (event.data?.type === 'HARVEST_AUTH_REQUEST' && event.data?.platform === platform) {
        const connectionData = {
          platform: platform,
          credentials: event.data.credentials || {}
        };
        try {
          const savedConn = await api.saveUserConnection(1, connectionData);
          setConnections((prev) => ({
            ...prev,
            [platform]: {
              name: savedConn.account_name,
              handle: savedConn.account_handle,
              avatar: savedConn.account_avatar,
              credentials: savedConn.credentials || {}
            }
          }));
          setSelectedPlatforms((prev) => ({ ...prev, [platform]: true }));
          popup.postMessage({ type: 'HARVEST_AUTH_SUCCESS' }, '*');
          window.removeEventListener('message', handleAuthMessage);
        } catch (e) {
          console.error("Failed to save connection to DB:", e);
          const errorMsg = e.response?.data?.detail || e.message || "Failed to verify connection.";
          popup.postMessage({ type: 'HARVEST_AUTH_FAILURE', error: errorMsg }, '*');
        }
      }
      // 2. Direct authentication success from backend redirect OAuth callback
      else if (event.data?.type === 'HARVEST_AUTH_SUCCESS' && event.data?.platform === platform) {
        try {
          // Load updated connections from backend DB
          const data = await api.getUserConnections(1);
          const loaded = { youtube: null, facebook: null, instagram: null };
          data.forEach((conn) => {
            loaded[conn.platform] = {
              name: conn.account_name,
              handle: conn.account_handle,
              avatar: conn.account_avatar,
              credentials: conn.credentials || {},
            };
          });
          setConnections(loaded);
          setSelectedPlatforms((prev) => ({ ...prev, [platform]: true }));
        } catch (e) {
          console.error("Failed to sync connection after live login:", e);
        }
        window.removeEventListener('message', handleAuthMessage);
      }
    };

    window.addEventListener('message', handleAuthMessage);
  };

  const handleDisconnect = async (platform) => {
    try {
      await api.deleteUserConnection(1, platform);
      setConnections((prev) => ({
        ...prev,
        [platform]: null,
      }));
      setSelectedPlatforms((prev) => ({ ...prev, [platform]: false }));
    } catch (e) {
      console.error("Failed to disconnect from DB:", e);
      alert("Failed to disconnect from database.");
    }
  };

  const togglePlatformSelection = (platform) => {
    if (!connections[platform]) {
      handleConnect(platform);
      return;
    }
    setSelectedPlatforms((prev) => ({
      ...prev,
      [platform]: !prev[platform],
    }));
  };

  const handlePublish = async () => {
    const activePlatforms = Object.keys(selectedPlatforms).filter((k) => selectedPlatforms[k]);
    if (activePlatforms.length === 0) {
      alert('Please select at least one connected social platform to publish to.');
      return;
    }

    // Extract custom tokens/credentials if the connected account is configured with them
    const platformConfigs = {};
    activePlatforms.forEach((p) => {
      const conn = connections[p];
      if (conn && conn.credentials) {
        Object.keys(conn.credentials).forEach((k) => {
          platformConfigs[k] = conn.credentials[k];
        });
      }
    });

    setIsPublishing(true);
    setPublishSuccess(false);
    setPublishProgress([]);

    // Initialize progress items
    const steps = [];
    activePlatforms.forEach((p) => {
      steps.push({ platform: p, stage: 'handshake', label: 'Connecting to server API...', status: 'running' });
    });
    setPublishProgress(steps);

    try {
      // Trigger background publishing task on backend
      const res = await api.publishClip(clip.id, activePlatforms, title, description, privacy, platformConfigs);
      const taskId = res.task_id;

      // Start simulated step-by-step progress tracking for standard local flow
      let currentStep = 0;
      const progressSteps = [
        { stage: 'uploading', label: 'Transmitting video stream chunks (CRF 18)...' },
        { stage: 'metadata', label: 'Applying subtitle tracks and video SEO tags...' },
        { stage: 'indexing', label: 'Meta/Google API indexing process...' },
        { stage: 'success', label: 'Video published successfully!' },
      ];

      const interval = setInterval(() => {
        setPublishProgress((prev) => {
          const next = [...prev];
          let allDone = true;

          next.forEach((item) => {
            if (currentStep < progressSteps.length) {
              item.stage = progressSteps[currentStep].stage;
              item.label = progressSteps[currentStep].label;
              item.status = currentStep === progressSteps.length - 1 ? 'completed' : 'running';
              allDone = false;
            } else {
              item.status = 'completed';
            }
          });

          if (allDone) {
            clearInterval(interval);
            setIsPublishing(false);
            setPublishSuccess(true);
            
            // Build mock share URLs
            const mockUrls = {};
            if (selectedPlatforms.youtube) mockUrls.youtube = 'https://youtube.com/shorts/mock_shorts_id';
            if (selectedPlatforms.instagram) mockUrls.instagram = 'https://instagram.com/reel/mock_reel_id';
            if (selectedPlatforms.facebook) mockUrls.facebook = 'https://facebook.com/reel/mock_reel_id';
            setShareUrls(mockUrls);
          }

          return next;
        });

        currentStep++;
      }, 2000);

    } catch (e) {
      console.error(e);
      alert('Publishing failed: ' + e.message);
      setIsPublishing(false);
    }
  };

  const getPlatformIcon = (platform, size = 20) => {
    switch (platform) {
      case 'youtube':
        return <Youtube size={size} color="#ff0000" />;
      case 'facebook':
        return <Facebook size={size} color="#1877f2" />;
      case 'instagram':
        return <Instagram size={size} color="#e1306c" />;
      default:
        return null;
    }
  };

  const getPlatformLabel = (platform) => {
    switch (platform) {
      case 'youtube':
        return 'YouTube Shorts';
      case 'facebook':
        return 'Facebook Reels';
      case 'instagram':
        return 'Instagram Reels';
      default:
        return '';
    }
  };

  return (
    <div className="glass-panel" style={{ background: '#12121a', border: '1px solid rgba(255, 255, 255, 0.1)', padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', width: '100%', position: 'relative' }}>
      
      {onClose && (
        <button
          onClick={onClose}
          style={{ position: 'absolute', top: 20, right: 20, background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer' }}
        >
          <X size={20} />
        </button>
      )}

      <div>
        <h3 style={{ margin: 0, fontSize: '1.4rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
          <Share2 size={22} color="var(--accent-color)" /> Social Media Publishing
        </h3>
        <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
          Directly publish this short-form vertical video to your profiles
        </p>
      </div>

      {!isPublishing && !publishSuccess ? (
        <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap' }}>
          {/* Left Column: Platform Selection & Login */}
          <div style={{ flex: 1.2, display: 'flex', flexDirection: 'column', gap: '1.2rem', minWidth: 260 }}>
            <h4 style={{ margin: 0, fontSize: '0.95rem', color: '#c084fc', textTransform: 'uppercase', fontWeight: 700 }}>
              1. Choose Platforms
            </h4>

            {['instagram', 'facebook'].map((plat) => {
              const connected = connections[plat];
              const isSelected = selectedPlatforms[plat];

              return (
                <div
                  key={plat}
                  onClick={() => togglePlatformSelection(plat)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '1rem',
                    background: isSelected ? 'rgba(139, 92, 246, 0.08)' : 'rgba(255, 255, 255, 0.02)',
                    border: `1px solid ${isSelected ? '#8b5cf6' : 'rgba(255, 255, 255, 0.08)'}`,
                    borderRadius: 12,
                    cursor: 'pointer',
                    transition: 'all 0.2s',
                  }}
                  onMouseEnter={(e) => {
                    if (!isSelected) e.currentTarget.style.borderColor = 'rgba(255,255,255,0.2)';
                  }}
                  onMouseLeave={(e) => {
                    if (!isSelected) e.currentTarget.style.borderColor = 'rgba(255,255,255,0.08)';
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
                    <div style={{ padding: '0.4rem', background: 'rgba(0,0,0,0.2)', borderRadius: '8px' }}>
                      {getPlatformIcon(plat, 24)}
                    </div>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: '0.9rem' }}>{getPlatformLabel(plat)}</div>
                      <div style={{ fontSize: '0.75rem', color: connected ? '#10b981' : '#64748b' }}>
                        {connected ? `Connected: ${connected.name}` : 'Not Connected'}
                      </div>
                    </div>
                  </div>

                  {connected ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      {isSelected && <span style={{ color: '#8b5cf6', fontSize: '1.2rem' }}>✓</span>}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDisconnect(plat);
                        }}
                        style={{
                          background: 'rgba(239, 68, 68, 0.1)',
                          color: '#ef4444',
                          border: 'none',
                          padding: '4px 8px',
                          borderRadius: 6,
                          fontSize: '0.7rem',
                          cursor: 'pointer',
                          fontWeight: 'bold',
                        }}
                      >
                        Disconnect
                      </button>
                    </div>
                  ) : (
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleConnect(plat);
                      }}
                      style={{
                        background: 'rgba(255, 255, 255, 0.05)',
                        border: '1px solid rgba(255, 255, 255, 0.15)',
                        color: 'white',
                        padding: '6px 12px',
                        borderRadius: 8,
                        fontSize: '0.75rem',
                        cursor: 'pointer',
                        fontWeight: 'bold',
                      }}
                    >
                      Connect
                    </button>
                  )}
                </div>
              );
            })}
          </div>

          {/* Right Column: Metadata details */}
          <div style={{ flex: 1.8, display: 'flex', flexDirection: 'column', gap: '1rem', minWidth: 300 }}>
            <h4 style={{ margin: 0, fontSize: '0.95rem', color: '#c084fc', textTransform: 'uppercase', fontWeight: 700 }}>
              2. Metadata & SEO Settings
            </h4>

            {selectedPlatforms.youtube && (
              <div>
                <label style={{ display: 'block', marginBottom: '0.3rem', fontSize: '0.8rem', color: '#94a3b8' }}>
                  YouTube Shorts Title (Max 100)
                </label>
                <input
                  type="text"
                  className="input-field"
                  value={title}
                  maxLength={100}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Crazy Gaming Clip! #shorts"
                  style={{ width: '100%', fontSize: '0.85rem' }}
                />
              </div>
            )}

            <div>
              <label style={{ display: 'block', marginBottom: '0.3rem', fontSize: '0.8rem', color: '#94a3b8' }}>
                Description / Caption
              </label>
              <textarea
                className="input-field"
                value={description}
                rows={4}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Enter caption or post text..."
                style={{ width: '100%', fontSize: '0.85rem', resize: 'none', fontFamily: 'inherit' }}
              />
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#64748b', marginTop: '0.2rem' }}>
                <span>Use hashtags for viral reach!</span>
                <span>{description.length} chars</span>
              </div>
            </div>

            {selectedPlatforms.youtube && (
              <div>
                <label style={{ display: 'block', marginBottom: '0.3rem', fontSize: '0.8rem', color: '#94a3b8' }}>
                  Shorts Privacy Level
                </label>
                <select
                  value={privacy}
                  onChange={(e) => setPrivacy(e.target.value)}
                  style={{
                    background: 'rgba(0,0,0,0.3)',
                    color: 'white',
                    border: '1px solid rgba(255,255,255,0.1)',
                    borderRadius: '8px',
                    padding: '0.5rem',
                    width: '100%',
                    fontSize: '0.85rem',
                    outline: 'none',
                  }}
                >
                  <option value="public">🌐 Public (Immediate release)</option>
                  <option value="unlisted">🔗 Unlisted (Link access only)</option>
                  <option value="private">🔒 Private (Only you can view)</option>
                </select>
              </div>
            )}

            <button
              onClick={handlePublish}
              className="btn-neon"
              style={{
                width: '100%',
                padding: '0.8rem',
                fontSize: '0.95rem',
                fontWeight: 'bold',
                marginTop: '0.5rem',
              }}
            >
              🚀 Publish Selected Platforms
            </button>
          </div>
        </div>
      ) : isPublishing ? (
        /* Publishing Loader Stage */
        <div style={{ textAlign: 'center', padding: '2rem 1rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ repeat: Infinity, duration: 2, ease: 'linear' }}
            style={{ width: 48, height: 48, borderRadius: '50%', border: '3px solid rgba(139,92,246,0.2)', borderTopColor: '#8b5cf6', display: 'flex', alignItems: 'center', justify: 'center' }}
          />
          <div>
            <h4 style={{ margin: 0, fontSize: '1.2rem', color: '#fff' }}>Publishing in Progress</h4>
            <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: '#94a3b8' }}>
              Transmitting video chunks and applying SEO configs to platforms
            </p>
          </div>

          <div style={{ width: '100%', maxWidth: 450, background: 'rgba(0,0,0,0.3)', padding: '1.2rem', borderRadius: 12, border: '1px solid rgba(255,255,255,0.05)', display: 'flex', flexDirection: 'column', gap: '0.8rem', textAlign: 'left' }}>
            {publishProgress.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', alignItems: 'center', justify: 'space-between', fontSize: '0.85rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  {getPlatformIcon(item.platform, 16)}
                  <span style={{ fontWeight: 600 }}>{getPlatformLabel(item.platform)}:</span>
                  <span style={{ color: '#cbd5e1' }}>{item.label}</span>
                </div>
                {item.status === 'completed' ? (
                  <span style={{ color: '#10b981', fontWeight: 600 }}>✓ Done</span>
                ) : (
                  <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1.5, ease: 'linear' }}>
                    <Loader size={14} color="#8b5cf6" />
                  </motion.div>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        /* Success State */
        <div style={{ textAlign: 'center', padding: '2.5rem 1rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', alignItems: 'center' }}>
          <div style={{ width: 64, height: 64, borderRadius: '50%', background: 'rgba(16,185,129,0.15)', border: '2px solid #10b981', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#10b981' }}>
            <CheckCircle2 size={32} />
          </div>
          <div>
            <h4 style={{ margin: 0, fontSize: '1.3rem', color: '#fff' }}>Publication Success!</h4>
            <p style={{ margin: '0.25rem 0 0', fontSize: '0.85rem', color: '#94a3b8' }}>
              Your clip parts have been published and are now processing on servers
            </p>
          </div>

          <div style={{ width: '100%', maxWidth: 450, display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
            {Object.keys(shareUrls).map((p) => (
              <a
                key={p}
                href={shareUrls[p]}
                target="_blank"
                rel="noreferrer"
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '1rem',
                  background: 'rgba(255,255,255,0.02)',
                  border: '1px solid rgba(255,255,255,0.08)',
                  borderRadius: 10,
                  color: 'white',
                  textDecoration: 'none',
                  fontSize: '0.9rem',
                  transition: 'background 0.2s',
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = 'rgba(255,255,255,0.05)')}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'rgba(255,255,255,0.02)')}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
                  {getPlatformIcon(p, 20)}
                  <span style={{ fontWeight: 600 }}>View on {getPlatformLabel(p)}</span>
                </div>
                <ExternalLink size={16} color="#94a3b8" />
              </a>
            ))}
          </div>

          <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem' }}>
            <button
              onClick={() => {
                setPublishSuccess(false);
                setIsPublishing(false);
              }}
              style={{
                padding: '0.6rem 1.5rem',
                background: 'rgba(255,255,255,0.05)',
                border: '1px solid rgba(255,255,255,0.15)',
                borderRadius: 8,
                color: 'white',
                cursor: 'pointer',
                fontSize: '0.85rem',
                fontWeight: 600,
              }}
            >
              Publish Again
            </button>
            {onClose && (
              <button
                onClick={onClose}
                className="btn-neon"
                style={{ padding: '0.6rem 1.5rem', fontSize: '0.85rem' }}
              >
                Close Panel
              </button>
            )}
          </div>
        </div>
      )}

      {/* Security note */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', justifyContent: 'center', borderTop: '1px solid rgba(255,255,255,0.04)', paddingTop: '1rem', fontSize: '0.75rem', color: '#475569' }}>
        <ShieldCheck size={14} /> Encrypted API Handshake. Content authorized via verified developer sandbox.
      </div>
    </div>
  );
}
