"""Add content understanding fields

Revision ID: 203cc0c482a2
Revises: ade4f00a8470
Create Date: 2026-06-09 02:37:55.511077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '203cc0c482a2'
down_revision: Union[str, None] = 'ade4f00a8470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('analysis_status', sa.Enum('NONE', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='contentanalysisstatus'), nullable=True))
    op.add_column('videos', sa.Column('content_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'content_analysis')
    op.drop_column('videos', 'analysis_status')
    # ### end Alembic commands ###
