"""Add highlight detection fields

Revision ID: 43c01ad11403
Revises: 203cc0c482a2
Create Date: 2026-06-09 02:58:01.981639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c01ad11403'
down_revision: Union[str, None] = '203cc0c482a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('highlight_status', sa.Enum('NONE', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='highlightdetectionstatus'), nullable=True))
    op.add_column('videos', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'highlights')
    op.drop_column('videos', 'highlight_status')
    # ### end Alembic commands ###
