"""Add smart cropping fields

Revision ID: 630b8b587a71
Revises: 43c01ad11403
Create Date: 2026-06-09 03:10:59.120368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '630b8b587a71'
down_revision: Union[str, None] = '43c01ad11403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cropstatus_enum = sa.Enum('NONE', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='cropstatus')
    cropstatus_enum.create(op.get_bind())
    op.add_column('videos', sa.Column('crop_status', cropstatus_enum, nullable=True))
    op.add_column('videos', sa.Column('crop_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'crop_metadata')
    op.drop_column('videos', 'crop_status')
    sa.Enum(name='cropstatus').drop(op.get_bind())
    # ### end Alembic commands ###
